volumes: 
  postgres-data: 
  redis-data: 
  server-data: 
 
services:
  postgres:
    image: postgres:15.3

    volumes: 
      - postgres-data:/var/lib/postgresql/data 
 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: koc

    ports: 
      - "5432:5432" 
 
  redis:
    image: redis:7.0.11

    volumes: 
      - redis-data:/data 
 
  server:
    image: ghcr.io/kocxyz/serverdocker
    build: .

    volumes: 
      - server-data:/data 
 
    environment:
      KOC_BACKEND_MAX_PLAYER_CONNECTIONS: 10
      KOC_SECRET:

      KOC_BACKEND_PORT: 23600
      KOC_SERVER_MIN_PORT: 23600
      KOC_SERVER_MAX_PORT: 23699

      KOC_BACKEND_DB: postgres://postgres:postgres@postgres:5432/koc
      KOC_BACKEND_REDIS_DB_HOST: redis
      KOC_BACKEND_REDIS_DB_PORT: 6379

    ports:
      - "23600:23600" 
      - "23600-23699:23600-23699/udp"

    depends_on:
      - redis
      - postgres